{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sfd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sfd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sfd/sfd_{{ version }}.tar.gz
  sha256: 631bd8ba300d2a55bb9cf47092ec9c7a6b5bb13ef2581ee43e7fbfdfbe5cce7d

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-rlang
    - r-tibble
  run:
    - r-base
    - r-cli
    - r-rlang
    - r-tibble

test:
  commands:
    - $R -e "library('sfd')"           # [not win]
    - "\"%R%\" -e \"library('sfd')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sfd
  license: MIT
  summary: A collection of pre-optimized space-filling designs, for up to ten parameters, is
    contained here. Functions are provided to access designs described by Husslage et
    al (2011) <doi:10.1007/s11081-010-9129-8> and Wang and Fang (2005) <doi:10.1142/9789812701190_0040>.
    The design types included are Audze-Eglais, MaxiMin, and uniform.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
